CGameCtrl = require "game.gamemain.CGameCtrl"
CPlayer = require "game.gamemain.CPlayer"

CGameView = require "game.gamemain.CGameView"
CBackgroundView = require "game.gamemain.CBackgroundView"
CPlayerInfoView = require "game.gamemain.CPlayerInfoView"
CLookShopView = require "game.gamemain.CLookShopView"
CYearView = require "game.gamemain.CYearView"
CShopView = require "game.gamemain.CShopView"

COptionView = require "game.gamemain.COptionView"
CTradeView = require "game.gamemain.CTradeView"
CSelectionView = require "game.gamemain.CSelectionView"
CGameChatView = require "game.gamemain.CGameChatView"
CRankView = require "game.gamemain.CRankView"
CHelpView = require "game.gamemain.CHelpView"

CLocation = require "game.gamemain.CLocation"
CPlayerInfo = require "game.gamemain.CPlayerInfo"
CShopCard = require "game.gamemain.CShopCard"
CTradeInfo = require "game.gamemain.CTradeInfo"
CTradeFlag = require "game.gamemain.CTradeFlag"
CSelectionGrid = require "game.gamemain.CSelectionGrid"
CRankInfo = require "game.gamemain.CRankInfo"